### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by master7720** [pastimee/shoreline#11]
java.lang.IllegalStateException: Already building!
	at net.minecraft.class_287.method_1328(class_287.java:109)
	at net.minecraft.class_4597$class_4598.getBuffer(class_4597.java:50)
	at net.minecraft.class_918.method_29711(class_918.java:218)
	at net.minecraft.class_918.method_23179(class_918.java:158)
	at net.minecraft.class_916.method_3996(class_916.java:101)
	at net.minecraft.class_916.method_3936(class_916.java:17)
	at net.minecraft.class_898.method_3954(class_898.java:146)
	at net.minecraft.class_761.method_22977(class_761.java:1348)
	at net.minecraft.class_761.method_22710(class_761.java:1098)
	at net.minecraft.class_757.method_3188(class_757.java:1098)
	at net.minecraft.class_757.method_3192(class_757.java:866)
	at net.minecraft.class_310.method_1523(class_310.java:1327)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_287.method_1328(class_287.java:109)
	at net.minecraft.class_4597$class_4598.getBuffer(class_4597.java:50)
	at net.minecraft.class_918.method_29711(class_918.java:218)
	at net.minecraft.class_918.method_23179(class_918.java:158)
	at net.minecraft.class_916.method_3996(class_916.java:101)
	at net.minecraft.class_916.method_3936(class_916.java:17)
	at net.minecraft.class_898.method_3954(class_898.java:146)
	at net.minecraft.class_761.method_22977(class_761.java:1348)
	at net.minecraft.class_761.method_22710(class_761.java:1098)
	at net.minecraft.class_757.method_3188(class_757.java:1098)

-- Entity being rendered --
Details:
	Entity Type: minecraft:item (net.minecraft.class_1542)
	Entity ID: 3331
	Entity Name: Book
	Entity's Exact location: 8.16, 134.44, -7.21
	Entity's Block location: World: (8,134,-8), Section: (at 8,6,8 in 0,8,-1; chunk contains blocks 0,-64,-16 to 15,319,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Entity's Momentum: 0.00, -0.04, 0.00
	Entity's Passengers: []
	Entity's Vehicle: class_1531['Armor Stand'/3330, l='ClientLevel', x=8.16, y=134.44, z=-7.21]
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:146)
	at net.minecraft.class_761.method_22977(class_761.java:1348)
	at net.minecraft.class_761.method_22710(class_761.java:1098)
	at net.minecraft.class_757.method_3188(class_757.java:1098)
	at net.minecraft.class_757.method_3192(class_757.java:866)
	at net.minecraft.class_310.method_1523(class_310.java:1327)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_916@74ba4e0c
	Location: 9.15,1.82,-5.39 - World: (9,1,-6), Section: (at 9,1,10 in 0,0,-1; chunk contains blocks 0,-64,-16 to 15,319,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Rotation: 0.0
	Delta: 0.2999907
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:146)
	at net.minecraft.class_761.method_22977(class_761.java:1348)
	at net.minecraft.class_761.method_22710(class_761.java:1098)
	at net.minecraft.class_757.method_3188(class_757.java:1098)
	at net.minecraft.class_757.method_3192(class_757.java:866)
	at net.minecraft.class_310.method_1523(class_310.java:1327)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Uptime --
Details:
	JVM uptime: 69.210s
	Wall uptime: 60.475s
	High-res time: 58.902s
	Client ticks: 1126 ticks / 56.300s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2564)
	at net.minecraft.class_310.method_54580(class_310.java:995)
	at net.minecraft.class_310.method_1514(class_310.java:908)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

**Comment by hockeyl8** [comment]
please send steps to reproduce

**Comment by master7720** [comment]
when i turned on chams

**Comment by master7720** [comment]
also esp does i too

**Comment by pastimee** [comment]
57e2628 fixed
